package GrimlockAdTesting.TestUtils;

public final class InappAdTags {

 public static final String REG3202 = "https://adserver.videohub.tv/preview?RI=0eD0x-MBUWxGi9L3SWt8Bw&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=835E9ACC20975DE718282E46B2917BD1&CI=9m289ntCK1yx0TY1sysXUg&filterScreenTypes=desktop,mobilephone,mobiletablet,ctv&advertiserName=QA_DO_NOT_ALTER%22&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3203 = "https://adserver.videohub.tv/preview?RI=0qVDB4RQ6XxaPtPJ6LvNPw&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=EB3C0E79452040BDF67C3F14F44A81FE&CI=EQRLslwxeX0ah-b4ofuB8A&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG2989 = "https://adserver.videohub.tv/preview?RI=o7tyPLQqFrqWEkJb5FoqAw&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=1226EC455D1426757CAB59DD8EFE74E3&CI=p6nD-bcpW9JfkYvulJo_5g&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3145 = "https://adserver.iad1.videohub.tv/preview?RI=1-dkcuipeojmRzgjApyJsw&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=bottom-right&usedACP=y&dspACP=TREMORVIDEO_BEHAVIOR&sig=71EFCA407693D144732B9AB56A99769F&CI=CJyIl4v2_y6M6Km5yUUeHg&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3146 = "https://adserver.iad1.videohub.tv/preview?RI=-SaehNA-LBahAEmTSQd9xQ&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=bottom-right&usedACP=y&dspACP=TREMORVIDEO_BEHAVIOR&sig=88B3DFD329EEA0DF50CA31BCE2650C72&CI=Z8SYoL8B-E-o11dhjWDIqw&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG2996 = "https://adserver.videohub.tv/preview?RI=eD91ACUtU1oz714B3brUfw&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=B6D9AF799F73AEAE605CE72AB37FF603&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3253 = "https://adserver.videohub.tv/preview?RI=xaOz9fFLjiDZzi9qa7iAcA&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=98FDBD263F16C732528927A60086E888&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3258 = "https://adserver.videohub.tv/preview?RI=BUtl2Kh9i3PugIeOUJmflg&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=7033DCFC187C1AAC32C072F91DB015F6&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3199 = "https://adserver.videohub.tv/preview?RI=1rvRGDNIOv1X5OWmuVl1rA&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=4BA20214698E50B99ED51FA0461D3F50&CI=6NDmYVVKZcBM7T9OaUs2UQ&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3212 = "https://wiki.tremorvideodsp.com/https:/adserver.videohub.tv/preview?RI=cRTYsXFYPmc3eYkZaKjiXQ&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=4B838558EDEE2AA5BEE7C650DD8F5678&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3213 = "https://adserver.videohub.tv/preview?RI=OcZsiEmbEP3YHRprojA3yg&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=D54AE8E7B953B38D5F975EBE2A252400&dmps=y&ssRmlApp=1&isApp=y";
 public static final String REG3214 = "https://adserver.videohub.tv/preview?RI=l2MDuCADwN6wYRUVBdzQNg&screenType=mobiletablet&rml=true&Uctry=__country__&Ust=__state__&Udma=__dma__&Uzip=__postalCode__&Ucty=__city__&Uctnt=__continent__&Ulong=__longitude__&Ulat=__latitude__&Uacd=__areaCode__&position_ACP=__adChoicesPosition__&usedACP=__usedACP__&dspACP=__adChoicesProviders__&sig=6D09EBBF41733FD71A155D75412B6434&dmps=y&ssRmlApp=1&isApp=y";
}

